/**
 * Single registration wrapper for the app-shell service worker (/sw.js).
 *
 * Generated by vite-plugin-pwa (generateSW). We register only from this module.
 * Registration is REFUSED in any context where a stale cache would break the
 * Lovable preview or the developer environment:
 *   - not a production build (dev / HMR)
 *   - inside an iframe (Lovable editor preview)
 *   - Lovable preview / published hostnames
 *   - the current URL carries ?sw=off (manual kill switch)
 *
 * In every refused context we unregister any matching /sw.js first, so a
 * previously-registered worker from a production visit does not linger.
 */

const SW_PATH = "/sw.js";

function isLovableHostname(host: string): boolean {
  return (
    host.startsWith("id-preview--") ||
    host.startsWith("preview--") ||
    host === "lovableproject.com" ||
    host.endsWith(".lovableproject.com") ||
    host === "lovableproject-dev.com" ||
    host.endsWith(".lovableproject-dev.com") ||
    host === "beta.lovable.dev" ||
    host.endsWith(".beta.lovable.dev")
  );
}

function shouldRefuseRegistration(): boolean {
  if (!import.meta.env.PROD) return true;
  if (typeof window === "undefined") return true;
  if (window.self !== window.top) return true; // running inside an iframe
  if (isLovableHostname(window.location.hostname)) return true;
  const params = new URLSearchParams(window.location.search);
  if (params.get("sw") === "off") return true; // kill switch
  return false;
}

async function unregisterMatching(): Promise<void> {
  try {
    const registrations = await navigator.serviceWorker.getRegistrations();
    await Promise.all(
      registrations
        .filter((reg) => {
          const script = reg.active?.scriptURL ?? "";
          return script.endsWith(SW_PATH);
        })
        .map((reg) => reg.unregister()),
    );
  } catch {
    /* ignore — best-effort cleanup */
  }
}

export async function registerSW(): Promise<void> {
  if (typeof navigator === "undefined" || !("serviceWorker" in navigator)) {
    return;
  }

  if (shouldRefuseRegistration()) {
    await unregisterMatching();
    return;
  }

  try {
    await navigator.serviceWorker.register(SW_PATH, { scope: "/" });
  } catch (error) {
    console.warn("Não foi possível registrar o service worker:", error);
  }
}
